// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `Foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var argo = __M.module("argo");

    argo.Foo = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::argo::Foo"
        ],
        -1, undefined, undefined, false);

    argo.FooPrx = Slice.defineProxy(Ice.ObjectPrx, argo.Foo.ice_staticId, undefined);

    Slice.defineOperations(argo.Foo, argo.FooPrx,
    {
        "doit": [, , , , , [7], , , , , ],
        "doitAgain": [, , , , , [7], , , , , ]
    });
    exports.argo = argo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
