/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module complexmodule;

static import complexmodule_im;
static import tango.stdc.config;
static import tango.stdc.stringz;
static import tango.stdc.stringz;


class Complex {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin complexmodule_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          complexmodule_im.delete_Complex(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public void x(int value) {
    complexmodule_im.Complex_x_set(cast(void*)swigCPtr, value);
  }

  public int x() {
    auto ret = complexmodule_im.Complex_x_get(cast(void*)swigCPtr);
    return ret;
  }

  public void y(int value) {
    complexmodule_im.Complex_y_set(cast(void*)swigCPtr, value);
  }

  public int y() {
    auto ret = complexmodule_im.Complex_y_get(cast(void*)swigCPtr);
    return ret;
  }

  public int getX() {
    auto ret = complexmodule_im.Complex_getX(cast(void*)swigCPtr);
    return ret;
  }

  public int getY() {
    auto ret = complexmodule_im.Complex_getY(cast(void*)swigCPtr);
    return ret;
  }

  public this(int x_, int y_) {
    this(complexmodule_im.new_Complex__SWIG_0(x_, y_), true);
  }

  public this(int x_) {
    this(complexmodule_im.new_Complex__SWIG_1(x_), true);
  }

  public this() {
    this(complexmodule_im.new_Complex__SWIG_2(), true);
  }

  public Complex opAdd(Complex rhs) {
    Complex ret = new Complex(complexmodule_im.Complex_opAdd(cast(void*)swigCPtr, Complex.swigGetCPtr(rhs)), true);
    if (complexmodule_im.SwigPendingException.isPending) throw complexmodule_im.SwigPendingException.retrieve();
    return ret;
  }

  public Complex opSub(Complex rhs) {
    Complex ret = new Complex(complexmodule_im.Complex_opSub(cast(void*)swigCPtr, Complex.swigGetCPtr(rhs)), true);
    if (complexmodule_im.SwigPendingException.isPending) throw complexmodule_im.SwigPendingException.retrieve();
    return ret;
  }

  public char[] toString() {
    char[] ret = tango.stdc.stringz.fromStringz(complexmodule_im.Complex_toString(cast(void*)swigCPtr));
    return ret;
  }

  public char[] __repr__() {
    char[] ret = tango.stdc.stringz.fromStringz(complexmodule_im.Complex___repr__(cast(void*)swigCPtr));
    return ret;
  }
}
