import builders

env = Environment(CPPFLAGS = ['--std=c++14', '-I.'],
                  LIBPATH = ['/usr/lib/x86_64-linux-gnu/c++11'])

#env.Slice2cpp(target = 'Security', source = 'slice/Security.ice')
builders.addSlice2cppBuilder(env)

env.Slice2cpp(target = 'Foo', source = '../slice/Foo.ice')

foo = env.Object(source = 'Foo.cpp')

env.Program('simpleCppApp.cpp',
            LIBS = ['Ice', 'IceUtil', foo, 'pthread'])
