// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Ticker.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Ticker.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __argo__TickListener__onTick_name = "onTick";

const ::std::string __argo__TickListener__onImage_name = "onImage";

const ::std::string __argo__TickerPlant__subscribe_name = "subscribe";

const ::std::string __argo__TickerPlant__subscribeWithIdent_name = "subscribeWithIdent";

const ::std::string __argo__TickerPlant__sayHello_name = "sayHello";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::argo::upCast(::IceProxy::argo::TickListener* p) { return p; }

void
::IceProxy::argo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::argo::TickListener>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::argo::TickListener;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::argo::TickListener::onTick(const ::argo::TickSeq& __p_t, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __argo__TickListener__onTick_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_t);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::argo::TickListener::begin_onTick(const ::argo::TickSeq& __p_t, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __argo__TickListener__onTick_name, __del, __cookie);
    try
    {
        __result->prepare(__argo__TickListener__onTick_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_t);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::argo::TickListener::end_onTick(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __argo__TickListener__onTick_name);
}

void
IceProxy::argo::TickListener::onImage(const ::argo::TickImage& __p_img, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __argo__TickListener__onImage_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_img);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::argo::TickListener::begin_onImage(const ::argo::TickImage& __p_img, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __argo__TickListener__onImage_name, __del, __cookie);
    try
    {
        __result->prepare(__argo__TickListener__onImage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_img);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::argo::TickListener::end_onImage(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __argo__TickListener__onImage_name);
}

const ::std::string&
IceProxy::argo::TickListener::ice_staticId()
{
    return ::argo::TickListener::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::argo::TickListener::__newInstance() const
{
    return new TickListener;
}
::IceProxy::Ice::Object* ::IceProxy::argo::upCast(::IceProxy::argo::TickerPlant* p) { return p; }

void
::IceProxy::argo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::argo::TickerPlant>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::argo::TickerPlant;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::argo::TickerPlant::subscribe(const ::argo::TickListenerPrx& __p_l, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __argo__TickerPlant__subscribe_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_l);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::argo::TickerPlant::begin_subscribe(const ::argo::TickListenerPrx& __p_l, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __argo__TickerPlant__subscribe_name, __del, __cookie);
    try
    {
        __result->prepare(__argo__TickerPlant__subscribe_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_l);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::argo::TickerPlant::end_subscribe(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __argo__TickerPlant__subscribe_name);
}

void
IceProxy::argo::TickerPlant::subscribeWithIdent(const ::Ice::Identity& __p_ident, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __argo__TickerPlant__subscribeWithIdent_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_ident);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::argo::TickerPlant::begin_subscribeWithIdent(const ::Ice::Identity& __p_ident, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __argo__TickerPlant__subscribeWithIdent_name, __del, __cookie);
    try
    {
        __result->prepare(__argo__TickerPlant__subscribeWithIdent_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_ident);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::argo::TickerPlant::end_subscribeWithIdent(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __argo__TickerPlant__subscribeWithIdent_name);
}

::std::string
IceProxy::argo::TickerPlant::sayHello(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__argo__TickerPlant__sayHello_name);
    ::IceInternal::Outgoing __og(this, __argo__TickerPlant__sayHello_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::std::string __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::argo::TickerPlant::begin_sayHello(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__argo__TickerPlant__sayHello_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __argo__TickerPlant__sayHello_name, __del, __cookie);
    try
    {
        __result->prepare(__argo__TickerPlant__sayHello_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::argo::TickerPlant::__begin_sayHello(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::argo::TickerPlantPrx __proxy = ::argo::TickerPlantPrx::uncheckedCast(__result->getProxy());
            ::std::string __ret;
            try
            {
                __ret = __proxy->end_sayHello(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::std::string&)> _response;
    };
    return begin_sayHello(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::std::string
IceProxy::argo::TickerPlant::end_sayHello(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __argo__TickerPlant__sayHello_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::argo::TickerPlant::ice_staticId()
{
    return ::argo::TickerPlant::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::argo::TickerPlant::__newInstance() const
{
    return new TickerPlant;
}

::Ice::Object* argo::upCast(::argo::TickListener* p) { return p; }

namespace
{
const ::std::string __argo__TickListener_ids[2] =
{
    "::Ice::Object",
    "::argo::TickListener"
};

}

bool
argo::TickListener::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__argo__TickListener_ids, __argo__TickListener_ids + 2, _s);
}

::std::vector< ::std::string>
argo::TickListener::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__argo__TickListener_ids[0], &__argo__TickListener_ids[2]);
}

const ::std::string&
argo::TickListener::ice_id(const ::Ice::Current&) const
{
    return __argo__TickListener_ids[1];
}

const ::std::string&
argo::TickListener::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::argo::TickListener";
    return typeId;
#else
    return __argo__TickListener_ids[1];
#endif
}

::Ice::DispatchStatus
argo::TickListener::___onTick(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::argo::TickSeq __p_t;
    __is->read(__p_t);
    __inS.endReadParams();
    onTick(__p_t, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
argo::TickListener::___onImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::argo::TickImage __p_img;
    __is->read(__p_img);
    __inS.endReadParams();
    onImage(__p_img, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __argo__TickListener_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "onImage",
    "onTick"
};

}

::Ice::DispatchStatus
argo::TickListener::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__argo__TickListener_all, __argo__TickListener_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __argo__TickListener_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___onImage(in, current);
        }
        case 5:
        {
            return ___onTick(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
argo::TickListener::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
argo::TickListener::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
argo::__patch(TickListenerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::argo::TickListenerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::argo::TickListener::ice_staticId(), v);
    }
}

::Ice::Object* argo::upCast(::argo::TickerPlant* p) { return p; }

namespace
{
const ::std::string __argo__TickerPlant_ids[2] =
{
    "::Ice::Object",
    "::argo::TickerPlant"
};

}

bool
argo::TickerPlant::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__argo__TickerPlant_ids, __argo__TickerPlant_ids + 2, _s);
}

::std::vector< ::std::string>
argo::TickerPlant::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__argo__TickerPlant_ids[0], &__argo__TickerPlant_ids[2]);
}

const ::std::string&
argo::TickerPlant::ice_id(const ::Ice::Current&) const
{
    return __argo__TickerPlant_ids[1];
}

const ::std::string&
argo::TickerPlant::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::argo::TickerPlant";
    return typeId;
#else
    return __argo__TickerPlant_ids[1];
#endif
}

::Ice::DispatchStatus
argo::TickerPlant::___subscribe(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::argo::TickListenerPrx __p_l;
    __is->read(__p_l);
    __inS.endReadParams();
    subscribe(__p_l, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
argo::TickerPlant::___subscribeWithIdent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Identity __p_ident;
    __is->read(__p_ident);
    __inS.endReadParams();
    subscribeWithIdent(__p_ident, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
argo::TickerPlant::___sayHello(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::std::string __ret = sayHello(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __argo__TickerPlant_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sayHello",
    "subscribe",
    "subscribeWithIdent"
};

}

::Ice::DispatchStatus
argo::TickerPlant::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__argo__TickerPlant_all, __argo__TickerPlant_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __argo__TickerPlant_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___sayHello(in, current);
        }
        case 5:
        {
            return ___subscribe(in, current);
        }
        case 6:
        {
            return ___subscribeWithIdent(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
argo::TickerPlant::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
argo::TickerPlant::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
argo::__patch(TickerPlantPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::argo::TickerPlantPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::argo::TickerPlant::ice_staticId(), v);
    }
}
