// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Ticker.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Ticker_h__
#define __Ticker_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/Identity.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace argo
{

class TickListener;
class TickListenerPrx;
class TickerPlant;
class TickerPlantPrx;

}

namespace argo
{

enum class TickDirection : unsigned char
{
    ZERO,
    UP,
    DOWN
};

struct Tick
{
    ::std::string symbol;
    double bidPx;
    double askPx;
    ::argo::TickDirection bidDirection;
    ::argo::TickDirection askDirection;

    std::tuple<const ::std::string&, const double&, const double&, const ::argo::TickDirection&, const ::argo::TickDirection&> ice_tuple() const
    {
        return std::tie(symbol, bidPx, askPx, bidDirection, askDirection);
    }
};

using TickSeq = ::std::vector<::argo::Tick>;

using TickImage = ::std::vector<::argo::TickSeq>;

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace argo
{

class TickListener : public virtual ::Ice::Object
{
public:

    using ProxyType = TickListenerPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void onTick(::argo::TickSeq, const ::Ice::Current&) = 0;
    bool _iceD_onTick(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void onImage(::argo::TickImage, const ::Ice::Current&) = 0;
    bool _iceD_onImage(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

class TickerPlant : public virtual ::Ice::Object
{
public:

    using ProxyType = TickerPlantPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void subscribe(::std::shared_ptr<::argo::TickListenerPrx>, const ::Ice::Current&) = 0;
    bool _iceD_subscribe(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void subscribeWithIdent(::Ice::Identity, const ::Ice::Current&) = 0;
    bool _iceD_subscribeWithIdent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string sayHello(const ::Ice::Current&) = 0;
    bool _iceD_sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace argo
{

class TickListenerPrx : public virtual ::Ice::Proxy<TickListenerPrx, ::Ice::ObjectPrx>
{
public:

    void onTick(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &argo::TickListenerPrx::_iceI_onTick, iceP_t, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto onTickAsync(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &argo::TickListenerPrx::_iceI_onTick, iceP_t, context);
    }

    ::std::function<void()>
    onTickAsync(const ::argo::TickSeq& iceP_t,
                ::std::function<void()> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &argo::TickListenerPrx::_iceI_onTick, iceP_t, context);
    }

    void _iceI_onTick(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::argo::TickSeq&, const ::Ice::Context&);

    void onImage(const ::argo::TickImage& iceP_img, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &argo::TickListenerPrx::_iceI_onImage, iceP_img, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto onImageAsync(const ::argo::TickImage& iceP_img, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &argo::TickListenerPrx::_iceI_onImage, iceP_img, context);
    }

    ::std::function<void()>
    onImageAsync(const ::argo::TickImage& iceP_img,
                 ::std::function<void()> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &argo::TickListenerPrx::_iceI_onImage, iceP_img, context);
    }

    void _iceI_onImage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::argo::TickImage&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    TickListenerPrx() = default;
    friend ::std::shared_ptr<TickListenerPrx> IceInternal::createProxy<TickListenerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

class TickerPlantPrx : public virtual ::Ice::Proxy<TickerPlantPrx, ::Ice::ObjectPrx>
{
public:

    void subscribe(const ::std::shared_ptr<::argo::TickListenerPrx>& iceP_l, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &argo::TickerPlantPrx::_iceI_subscribe, iceP_l, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto subscribeAsync(const ::std::shared_ptr<::argo::TickListenerPrx>& iceP_l, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &argo::TickerPlantPrx::_iceI_subscribe, iceP_l, context);
    }

    ::std::function<void()>
    subscribeAsync(const ::std::shared_ptr<::argo::TickListenerPrx>& iceP_l,
                   ::std::function<void()> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &argo::TickerPlantPrx::_iceI_subscribe, iceP_l, context);
    }

    void _iceI_subscribe(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::std::shared_ptr<::argo::TickListenerPrx>&, const ::Ice::Context&);

    void subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &argo::TickerPlantPrx::_iceI_subscribeWithIdent, iceP_ident, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto subscribeWithIdentAsync(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &argo::TickerPlantPrx::_iceI_subscribeWithIdent, iceP_ident, context);
    }

    ::std::function<void()>
    subscribeWithIdentAsync(const ::Ice::Identity& iceP_ident,
                            ::std::function<void()> response,
                            ::std::function<void(::std::exception_ptr)> ex = nullptr,
                            ::std::function<void(bool)> sent = nullptr,
                            const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &argo::TickerPlantPrx::_iceI_subscribeWithIdent, iceP_ident, context);
    }

    void _iceI_subscribeWithIdent(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Identity&, const ::Ice::Context&);

    ::std::string sayHello(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::std::string>(true, this, &argo::TickerPlantPrx::_iceI_sayHello, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sayHelloAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::std::string>>().get_future())
    {
        return _makePromiseOutgoing<::std::string, P>(false, this, &argo::TickerPlantPrx::_iceI_sayHello, context);
    }

    ::std::function<void()>
    sayHelloAsync(::std::function<void(::std::string)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::std::string>(response, ex, sent, this, &argo::TickerPlantPrx::_iceI_sayHello, context);
    }

    void _iceI_sayHello(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    TickerPlantPrx() = default;
    friend ::std::shared_ptr<TickerPlantPrx> IceInternal::createProxy<TickerPlantPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

template<>
struct StreamableTraits< ::argo::TickDirection>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 2;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits<::argo::Tick>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 19;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::argo::Tick, S>
{
    static void read(S* istr, ::argo::Tick& v)
    {
        istr->readAll(v.symbol, v.bidPx, v.askPx, v.bidDirection, v.askDirection);
    }
};

}

namespace argo
{

using TickListenerPtr = ::std::shared_ptr<TickListener>;
using TickListenerPrxPtr = ::std::shared_ptr<TickListenerPrx>;

using TickerPlantPtr = ::std::shared_ptr<TickerPlant>;
using TickerPlantPrxPtr = ::std::shared_ptr<TickerPlantPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace argo
{

class TickListener;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::argo::TickListener>&);
::IceProxy::Ice::Object* upCast(::IceProxy::argo::TickListener*);

class TickerPlant;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::argo::TickerPlant>&);
::IceProxy::Ice::Object* upCast(::IceProxy::argo::TickerPlant*);

}

}

namespace argo
{

class TickListener;
::Ice::Object* upCast(::argo::TickListener*);
typedef ::IceInternal::Handle< ::argo::TickListener> TickListenerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::argo::TickListener> TickListenerPrx;
typedef TickListenerPrx TickListenerPrxPtr;
void _icePatchObjectPtr(TickListenerPtr&, const ::Ice::ObjectPtr&);

class TickerPlant;
::Ice::Object* upCast(::argo::TickerPlant*);
typedef ::IceInternal::Handle< ::argo::TickerPlant> TickerPlantPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::argo::TickerPlant> TickerPlantPrx;
typedef TickerPlantPrx TickerPlantPrxPtr;
void _icePatchObjectPtr(TickerPlantPtr&, const ::Ice::ObjectPtr&);

}

namespace argo
{

enum TickDirection
{
    ZERO,
    UP,
    DOWN
};

struct Tick
{
    ::std::string symbol;
    ::Ice::Double bidPx;
    ::Ice::Double askPx;
    ::argo::TickDirection bidDirection;
    ::argo::TickDirection askDirection;
};

typedef ::std::vector< ::argo::Tick> TickSeq;

typedef ::std::vector< ::argo::TickSeq> TickImage;

}

namespace argo
{

class Callback_TickListener_onTick_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TickListener_onTick_Base> Callback_TickListener_onTickPtr;

class Callback_TickListener_onImage_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TickListener_onImage_Base> Callback_TickListener_onImagePtr;

class Callback_TickerPlant_subscribe_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TickerPlant_subscribe_Base> Callback_TickerPlant_subscribePtr;

class Callback_TickerPlant_subscribeWithIdent_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TickerPlant_subscribeWithIdent_Base> Callback_TickerPlant_subscribeWithIdentPtr;

class Callback_TickerPlant_sayHello_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TickerPlant_sayHello_Base> Callback_TickerPlant_sayHelloPtr;

}

namespace IceProxy
{

namespace argo
{

class TickListener : public virtual ::Ice::Proxy<TickListener, ::IceProxy::Ice::Object>
{
public:

    void onTick(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_onTick(_iceI_begin_onTick(iceP_t, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_onTick(iceP_t, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::argo::TickSeq& iceP_t, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onTick(iceP_t, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onTick(iceP_t, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::argo::TickSeq& iceP_t, const ::argo::Callback_TickListener_onTickPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onTick(iceP_t, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onTick(const ::argo::TickSeq& iceP_t, const ::Ice::Context& context, const ::argo::Callback_TickListener_onTickPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onTick(iceP_t, context, del, cookie);
    }

    void end_onTick(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_onTick(const ::argo::TickSeq&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void onImage(const ::argo::TickImage& iceP_img, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_onImage(_iceI_begin_onImage(iceP_img, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_onImage(const ::argo::TickImage& iceP_img, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_onImage(iceP_img, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_onImage(const ::argo::TickImage& iceP_img, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onImage(iceP_img, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onImage(const ::argo::TickImage& iceP_img, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onImage(iceP_img, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onImage(const ::argo::TickImage& iceP_img, const ::argo::Callback_TickListener_onImagePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onImage(iceP_img, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_onImage(const ::argo::TickImage& iceP_img, const ::Ice::Context& context, const ::argo::Callback_TickListener_onImagePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_onImage(iceP_img, context, del, cookie);
    }

    void end_onImage(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_onImage(const ::argo::TickImage&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

class TickerPlant : public virtual ::Ice::Proxy<TickerPlant, ::IceProxy::Ice::Object>
{
public:

    void subscribe(const ::argo::TickListenerPrx& iceP_l, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_subscribe(_iceI_begin_subscribe(iceP_l, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_subscribe(const ::argo::TickListenerPrx& iceP_l, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_subscribe(iceP_l, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_subscribe(const ::argo::TickListenerPrx& iceP_l, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribe(iceP_l, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribe(const ::argo::TickListenerPrx& iceP_l, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribe(iceP_l, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribe(const ::argo::TickListenerPrx& iceP_l, const ::argo::Callback_TickerPlant_subscribePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribe(iceP_l, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribe(const ::argo::TickListenerPrx& iceP_l, const ::Ice::Context& context, const ::argo::Callback_TickerPlant_subscribePtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribe(iceP_l, context, del, cookie);
    }

    void end_subscribe(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_subscribe(const ::argo::TickListenerPrx&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_subscribeWithIdent(_iceI_begin_subscribeWithIdent(iceP_ident, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_subscribeWithIdent(iceP_ident, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribeWithIdent(iceP_ident, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribeWithIdent(iceP_ident, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::argo::Callback_TickerPlant_subscribeWithIdentPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribeWithIdent(iceP_ident, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_subscribeWithIdent(const ::Ice::Identity& iceP_ident, const ::Ice::Context& context, const ::argo::Callback_TickerPlant_subscribeWithIdentPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_subscribeWithIdent(iceP_ident, context, del, cookie);
    }

    void end_subscribeWithIdent(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_subscribeWithIdent(const ::Ice::Identity&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::std::string sayHello(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_sayHello(_iceI_begin_sayHello(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sayHello(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::argo::Callback_TickerPlant_sayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::Ice::Context& context, const ::argo::Callback_TickerPlant_sayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(context, del, cookie);
    }

    ::std::string end_sayHello(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sayHello(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace argo
{

class TickListener : public virtual ::Ice::Object
{
public:

    typedef TickListenerPrx ProxyType;
    typedef TickListenerPtr PointerType;

    virtual ~TickListener();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void onTick(const ::argo::TickSeq&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_onTick(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void onImage(const ::argo::TickImage&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_onImage(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const TickListener& lhs, const TickListener& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const TickListener& lhs, const TickListener& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

class TickerPlant : public virtual ::Ice::Object
{
public:

    typedef TickerPlantPrx ProxyType;
    typedef TickerPlantPtr PointerType;

    virtual ~TickerPlant();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void subscribe(const ::argo::TickListenerPrx&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_subscribe(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void subscribeWithIdent(const ::Ice::Identity&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_subscribeWithIdent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string sayHello(const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const TickerPlant& lhs, const TickerPlant& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const TickerPlant& lhs, const TickerPlant& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

template<>
struct StreamableTraits< ::argo::TickDirection>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 2;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::argo::Tick>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 19;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::argo::Tick, S>
{
    static void write(S* ostr, const ::argo::Tick& v)
    {
        ostr->write(v.symbol);
        ostr->write(v.bidPx);
        ostr->write(v.askPx);
        ostr->write(v.bidDirection);
        ostr->write(v.askDirection);
    }
};

template<typename S>
struct StreamReader< ::argo::Tick, S>
{
    static void read(S* istr, ::argo::Tick& v)
    {
        istr->read(v.symbol);
        istr->read(v.bidPx);
        istr->read(v.askPx);
        istr->read(v.bidDirection);
        istr->read(v.askDirection);
    }
};

}

namespace argo
{

template<class T>
class CallbackNC_TickListener_onTick : public Callback_TickListener_onTick_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TickListener_onTick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onTick<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onTick<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onTick<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onTick<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TickListener_onTick : public Callback_TickListener_onTick_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TickListener_onTick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onTick<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onTick<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onTick<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onTickPtr
newCallback_TickListener_onTick(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onTick<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_TickListener_onImage : public Callback_TickListener_onImage_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TickListener_onImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onImage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onImage<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onImage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickListener_onImage<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TickListener_onImage : public Callback_TickListener_onImage_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TickListener_onImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onImage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onImage<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onImage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickListener_onImagePtr
newCallback_TickListener_onImage(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickListener_onImage<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_TickerPlant_subscribe : public Callback_TickerPlant_subscribe_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TickerPlant_subscribe(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribe<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribe<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribe<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribe<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TickerPlant_subscribe : public Callback_TickerPlant_subscribe_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TickerPlant_subscribe(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribe<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribe<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribe<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribePtr
newCallback_TickerPlant_subscribe(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribe<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_TickerPlant_subscribeWithIdent : public Callback_TickerPlant_subscribeWithIdent_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TickerPlant_subscribeWithIdent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribeWithIdent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribeWithIdent<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribeWithIdent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_subscribeWithIdent<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TickerPlant_subscribeWithIdent : public Callback_TickerPlant_subscribeWithIdent_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TickerPlant_subscribeWithIdent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribeWithIdent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribeWithIdent<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribeWithIdent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_subscribeWithIdentPtr
newCallback_TickerPlant_subscribeWithIdent(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_subscribeWithIdent<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_TickerPlant_sayHello : public Callback_TickerPlant_sayHello_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_TickerPlant_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::TickerPlantPrx proxy = ::argo::TickerPlantPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_sayHello(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_TickerPlant_sayHelloPtr
newCallback_TickerPlant_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TickerPlant_sayHelloPtr
newCallback_TickerPlant_sayHello(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TickerPlant_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_TickerPlant_sayHello : public Callback_TickerPlant_sayHello_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_TickerPlant_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::TickerPlantPrx proxy = ::argo::TickerPlantPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_sayHello(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_TickerPlant_sayHelloPtr
newCallback_TickerPlant_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TickerPlant_sayHelloPtr
newCallback_TickerPlant_sayHello(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TickerPlant_sayHello<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
