// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

import { Ice } from "ice";
const _ModuleRegistry = Ice._ModuleRegistry;
const Slice = Ice.Slice;

let Demo = _ModuleRegistry.module("Demo");

const iceC_Demo_Hello_ids = [
    "::Demo::Hello",
    "::Ice::Object"
];

Demo.Hello = class extends Ice.Object
{
};

Demo.HelloPrx = class extends Ice.ObjectPrx
{
};

Slice.defineOperations(Demo.Hello, Demo.HelloPrx, iceC_Demo_Hello_ids, 0,
{
    "sayHello": [, 2, 2, , [7], [[7]], , , , ]
});
export { Demo };
