// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `Discovery.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Discovery.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Demo__DiscoverReply__reply_name = "reply";

const ::std::string __Demo__Discover__lookup_name = "lookup";

}
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(::IceProxy::Demo::DiscoverReply* p) { return p; }

void
::IceProxy::Demo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Demo::DiscoverReply>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Demo::DiscoverReply;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Demo::DiscoverReply::reply(const ::Ice::ObjectPrx& __p_obj, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Demo__DiscoverReply__reply_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_obj);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Demo::DiscoverReply::begin_reply(const ::Ice::ObjectPrx& __p_obj, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Demo__DiscoverReply__reply_name, __del, __cookie);
    try
    {
        __result->prepare(__Demo__DiscoverReply__reply_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_obj);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Demo::DiscoverReply::end_reply(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Demo__DiscoverReply__reply_name);
}

const ::std::string&
IceProxy::Demo::DiscoverReply::ice_staticId()
{
    return ::Demo::DiscoverReply::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Demo::DiscoverReply::__newInstance() const
{
    return new DiscoverReply;
}
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(::IceProxy::Demo::Discover* p) { return p; }

void
::IceProxy::Demo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Demo::Discover>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Demo::Discover;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Demo::Discover::lookup(const ::Demo::DiscoverReplyPrx& __p_replyHere, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Demo__Discover__lookup_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_replyHere);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Demo::Discover::begin_lookup(const ::Demo::DiscoverReplyPrx& __p_replyHere, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Demo__Discover__lookup_name, __del, __cookie);
    try
    {
        __result->prepare(__Demo__Discover__lookup_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_replyHere);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Demo::Discover::end_lookup(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Demo__Discover__lookup_name);
}

const ::std::string&
IceProxy::Demo::Discover::ice_staticId()
{
    return ::Demo::Discover::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Demo::Discover::__newInstance() const
{
    return new Discover;
}

::Ice::Object* Demo::upCast(::Demo::DiscoverReply* p) { return p; }

namespace
{
const ::std::string __Demo__DiscoverReply_ids[2] =
{
    "::Demo::DiscoverReply",
    "::Ice::Object"
};

}

bool
Demo::DiscoverReply::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Demo__DiscoverReply_ids, __Demo__DiscoverReply_ids + 2, _s);
}

::std::vector< ::std::string>
Demo::DiscoverReply::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Demo__DiscoverReply_ids[0], &__Demo__DiscoverReply_ids[2]);
}

const ::std::string&
Demo::DiscoverReply::ice_id(const ::Ice::Current&) const
{
    return __Demo__DiscoverReply_ids[0];
}

const ::std::string&
Demo::DiscoverReply::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::DiscoverReply";
    return typeId;
#else
    return __Demo__DiscoverReply_ids[0];
#endif
}

::Ice::DispatchStatus
Demo::DiscoverReply::___reply(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::ObjectPrx __p_obj;
    __is->read(__p_obj);
    __inS.endReadParams();
    reply(__p_obj, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Demo__DiscoverReply_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "reply"
};

}

::Ice::DispatchStatus
Demo::DiscoverReply::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Demo__DiscoverReply_all, __Demo__DiscoverReply_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Demo__DiscoverReply_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___reply(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Demo::DiscoverReply::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Demo::DiscoverReply::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Demo::__patch(DiscoverReplyPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Demo::DiscoverReplyPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Demo::DiscoverReply::ice_staticId(), v);
    }
}

::Ice::Object* Demo::upCast(::Demo::Discover* p) { return p; }

namespace
{
const ::std::string __Demo__Discover_ids[2] =
{
    "::Demo::Discover",
    "::Ice::Object"
};

}

bool
Demo::Discover::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Demo__Discover_ids, __Demo__Discover_ids + 2, _s);
}

::std::vector< ::std::string>
Demo::Discover::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Demo__Discover_ids[0], &__Demo__Discover_ids[2]);
}

const ::std::string&
Demo::Discover::ice_id(const ::Ice::Current&) const
{
    return __Demo__Discover_ids[0];
}

const ::std::string&
Demo::Discover::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::Discover";
    return typeId;
#else
    return __Demo__Discover_ids[0];
#endif
}

::Ice::DispatchStatus
Demo::Discover::___lookup(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Demo::DiscoverReplyPrx __p_replyHere;
    __is->read(__p_replyHere);
    __inS.endReadParams();
    lookup(__p_replyHere, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Demo__Discover_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "lookup"
};

}

::Ice::DispatchStatus
Demo::Discover::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Demo__Discover_all, __Demo__Discover_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Demo__Discover_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___lookup(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Demo::Discover::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Demo::Discover::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Demo::__patch(DiscoverPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Demo::DiscoverPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Demo::Discover::ice_staticId(), v);
    }
}
