import builders

from os.path import expanduser as eu

SLICE_DIR = '/usr/share/ice/slice'
spdlog = '-I%s' % eu('~/repos/spdlog/include')

env = Environment(CPPFLAGS = ['--std=c++14',
                              '-I.',
                              spdlog,
                              '-g',
                              '-DICE_CPP11_MAPPING'],
                  CPPPATH=['/usr/include/SDL2'],
                  SLICE_INCLUDES = [SLICE_DIR] )

#env.Slice2cpp(target = 'Security', source = 'slice/Security.ice')
builders.addSlice2cppBuilder(env)

env.Slice2cpp(target = 'Foo',source = '../slice/Foo.ice')
env.Slice2cpp(target = 'Ticker',source = '../slice/Ticker.ice')

foo = env.Object(source = 'Foo.cpp')
server_adapter = env.Object(source = 'server_adapter.cpp')
#wrapped_string = env.Object('wrapped_string.d')

wrapped_string = env.Object("wrapped_string.cpp")

env.Program('simpled_server.d',
            LIBS = ['Ice++11',
                    server_adapter,
                    foo,
                    wrapped_string,
                    'pthread',
                    'stdc++'])

cpp_client = env.Program( 'cpp_client.cpp',
                          LIBS = ['Ice++11',
                                  foo,
                                  'pthread',
                                  'stdc++'])


