// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Foo_h__
#define __Foo_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace argo
{

class Foo;
class FooPrx;

}

namespace argo
{

class Foo : public virtual ::Ice::Object
{
public:

    using ProxyType = FooPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void doitAsync(::std::function<void(const ::std::string&)>, ::std::function<void(::std::exception_ptr)>, const ::Ice::Current&) = 0;
    bool _iceD_doit(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void doitAgainAsync(::std::function<void(const ::std::string&)>, ::std::function<void(::std::exception_ptr)>, const ::Ice::Current&) = 0;
    bool _iceD_doitAgain(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void addAsync(int, int, ::std::function<void(int)>, ::std::function<void(::std::exception_ptr)>, const ::Ice::Current&) = 0;
    bool _iceD_add(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace argo
{

class FooPrx : public virtual ::Ice::Proxy<FooPrx, ::Ice::ObjectPrx>
{
public:

    ::std::string doit(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::std::string>(true, this, &argo::FooPrx::_iceI_doit, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto doitAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::std::string>>().get_future())
    {
        return _makePromiseOutgoing<::std::string, P>(false, this, &argo::FooPrx::_iceI_doit, context);
    }

    ::std::function<void()>
    doitAsync(::std::function<void(::std::string)> response,
              ::std::function<void(::std::exception_ptr)> ex = nullptr,
              ::std::function<void(bool)> sent = nullptr,
              const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::std::string>(response, ex, sent, this, &argo::FooPrx::_iceI_doit, context);
    }

    void _iceI_doit(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>&, const ::Ice::Context&);

    ::std::string doitAgain(const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::std::string>(true, this, &argo::FooPrx::_iceI_doitAgain, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto doitAgainAsync(const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::std::string>>().get_future())
    {
        return _makePromiseOutgoing<::std::string, P>(false, this, &argo::FooPrx::_iceI_doitAgain, context);
    }

    ::std::function<void()>
    doitAgainAsync(::std::function<void(::std::string)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::std::string>(response, ex, sent, this, &argo::FooPrx::_iceI_doitAgain, context);
    }

    void _iceI_doitAgain(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>&, const ::Ice::Context&);

    int add(int iceP_a, int iceP_b, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<int>(true, this, &argo::FooPrx::_iceI_add, iceP_a, iceP_b, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto addAsync(int iceP_a, int iceP_b, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<int>>().get_future())
    {
        return _makePromiseOutgoing<int, P>(false, this, &argo::FooPrx::_iceI_add, iceP_a, iceP_b, context);
    }

    ::std::function<void()>
    addAsync(int iceP_a, int iceP_b,
             ::std::function<void(int)> response,
             ::std::function<void(::std::exception_ptr)> ex = nullptr,
             ::std::function<void(bool)> sent = nullptr,
             const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<int>(response, ex, sent, this, &argo::FooPrx::_iceI_add, iceP_a, iceP_b, context);
    }

    void _iceI_add(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    FooPrx() = default;
    friend ::std::shared_ptr<FooPrx> IceInternal::createProxy<FooPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

}

namespace argo
{

using FooPtr = ::std::shared_ptr<Foo>;
using FooPrxPtr = ::std::shared_ptr<FooPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace argo
{

class Foo;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::argo::Foo>&);
::IceProxy::Ice::Object* upCast(::IceProxy::argo::Foo*);

}

}

namespace argo
{

class Foo;
::Ice::Object* upCast(::argo::Foo*);
typedef ::IceInternal::Handle< ::argo::Foo> FooPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::argo::Foo> FooPrx;
typedef FooPrx FooPrxPtr;
void _icePatchObjectPtr(FooPtr&, const ::Ice::ObjectPtr&);

}

namespace argo
{

class AMD_Foo_doit : public virtual ::Ice::AMDCallback
{
public:

    virtual ~AMD_Foo_doit();

    virtual void ice_response(const ::std::string&) = 0;
};

typedef ::IceUtil::Handle< ::argo::AMD_Foo_doit> AMD_Foo_doitPtr;

class AMD_Foo_doitAgain : public virtual ::Ice::AMDCallback
{
public:

    virtual ~AMD_Foo_doitAgain();

    virtual void ice_response(const ::std::string&) = 0;
};

typedef ::IceUtil::Handle< ::argo::AMD_Foo_doitAgain> AMD_Foo_doitAgainPtr;

class AMD_Foo_add : public virtual ::Ice::AMDCallback
{
public:

    virtual ~AMD_Foo_add();

    virtual void ice_response(::Ice::Int) = 0;
};

typedef ::IceUtil::Handle< ::argo::AMD_Foo_add> AMD_Foo_addPtr;

}

namespace IceAsync
{

namespace argo
{

class AMD_Foo_doit : public ::argo::AMD_Foo_doit, public ::IceInternal::IncomingAsync
{
public:

    AMD_Foo_doit(::IceInternal::Incoming&);

    virtual void ice_response(const ::std::string&);
};

class AMD_Foo_doitAgain : public ::argo::AMD_Foo_doitAgain, public ::IceInternal::IncomingAsync
{
public:

    AMD_Foo_doitAgain(::IceInternal::Incoming&);

    virtual void ice_response(const ::std::string&);
};

class AMD_Foo_add : public ::argo::AMD_Foo_add, public ::IceInternal::IncomingAsync
{
public:

    AMD_Foo_add(::IceInternal::Incoming&);

    virtual void ice_response(::Ice::Int);
};

}

}

namespace argo
{

class Callback_Foo_doit_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Foo_doit_Base> Callback_Foo_doitPtr;

class Callback_Foo_doitAgain_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Foo_doitAgain_Base> Callback_Foo_doitAgainPtr;

class Callback_Foo_add_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Foo_add_Base> Callback_Foo_addPtr;

}

namespace IceProxy
{

namespace argo
{

class Foo : public virtual ::Ice::Proxy<Foo, ::IceProxy::Ice::Object>
{
public:

    ::std::string doit(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_doit(_iceI_begin_doit(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_doit(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_doit(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_doit(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doit(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doit(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doit(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doit(const ::argo::Callback_Foo_doitPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doit(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doit(const ::Ice::Context& context, const ::argo::Callback_Foo_doitPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doit(context, del, cookie);
    }

    ::std::string end_doit(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_doit(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::std::string doitAgain(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_doitAgain(_iceI_begin_doitAgain(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_doitAgain(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_doitAgain(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_doitAgain(const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doitAgain(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doitAgain(const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doitAgain(context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doitAgain(const ::argo::Callback_Foo_doitAgainPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doitAgain(::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_doitAgain(const ::Ice::Context& context, const ::argo::Callback_Foo_doitAgainPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_doitAgain(context, del, cookie);
    }

    ::std::string end_doitAgain(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_doitAgain(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::Ice::Int add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_add(_iceI_begin_add(iceP_a, iceP_b, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_add(iceP_a, iceP_b, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_add(iceP_a, iceP_b, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_add(iceP_a, iceP_b, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::argo::Callback_Foo_addPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_add(iceP_a, iceP_b, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_add(::Ice::Int iceP_a, ::Ice::Int iceP_b, const ::Ice::Context& context, const ::argo::Callback_Foo_addPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_add(iceP_a, iceP_b, context, del, cookie);
    }

    ::Ice::Int end_add(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_add(::Ice::Int, ::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace argo
{

class Foo : public virtual ::Ice::Object
{
public:

    typedef FooPrx ProxyType;
    typedef FooPtr PointerType;

    virtual ~Foo();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void doit_async(const ::argo::AMD_Foo_doitPtr&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_doit(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void doitAgain_async(const ::argo::AMD_Foo_doitAgainPtr&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_doitAgain(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void add_async(const ::argo::AMD_Foo_addPtr&, ::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_add(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const Foo& lhs, const Foo& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const Foo& lhs, const Foo& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

}

namespace argo
{

template<class T>
class CallbackNC_Foo_doit : public Callback_Foo_doit_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_Foo_doit(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_doit(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_Foo_doitPtr
newCallback_Foo_doit(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_doit<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Foo_doitPtr
newCallback_Foo_doit(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_doit<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Foo_doit : public Callback_Foo_doit_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_Foo_doit(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_doit(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_Foo_doitPtr
newCallback_Foo_doit(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_doit<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Foo_doitPtr
newCallback_Foo_doit(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_doit<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Foo_doitAgain : public Callback_Foo_doitAgain_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_Foo_doitAgain(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_doitAgain(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_Foo_doitAgainPtr
newCallback_Foo_doitAgain(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_doitAgain<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Foo_doitAgainPtr
newCallback_Foo_doitAgain(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_doitAgain<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Foo_doitAgain : public Callback_Foo_doitAgain_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_Foo_doitAgain(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_doitAgain(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_Foo_doitAgainPtr
newCallback_Foo_doitAgain(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_doitAgain<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Foo_doitAgainPtr
newCallback_Foo_doitAgain(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_doitAgain<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Foo_add : public Callback_Foo_add_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_Foo_add(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_add(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_Foo_addPtr
newCallback_Foo_add(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_add<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Foo_addPtr
newCallback_Foo_add(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Foo_add<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Foo_add : public Callback_Foo_add_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_Foo_add(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::argo::FooPrx proxy = ::argo::FooPrx::uncheckedCast(result->getProxy());
        ::Ice::Int ret;
        try
        {
            ret = proxy->end_add(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_Foo_addPtr
newCallback_Foo_add(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_add<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Foo_addPtr
newCallback_Foo_add(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Foo_add<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
