// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Foo.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_argo_Foo_ids[2] =
{
    "::Ice::Object",
    "::argo::Foo"
};
const ::std::string iceC_argo_Foo_ops[] =
{
    "doit",
    "doitAgain",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_argo_Foo_doit_name = "doit";
const ::std::string iceC_argo_Foo_doitAgain_name = "doitAgain";

}

bool
argo::Foo::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_argo_Foo_ids, iceC_argo_Foo_ids + 2, s);
}

::std::vector<::std::string>
argo::Foo::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_argo_Foo_ids[0], &iceC_argo_Foo_ids[2]);
}

::std::string
argo::Foo::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
argo::Foo::ice_staticId()
{
    static const ::std::string typeId = "::argo::Foo";
    return typeId;
}

bool
argo::Foo::_iceD_doit(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    auto inA = ::IceInternal::IncomingAsync::create(inS);
    auto responseCB = [inA](const ::std::string& ret)
    {
        auto ostr = inA->startWriteParams();
        ostr->writeAll(ret);
        inA->endWriteParams();
        inA->completed();
    };
    this->doitAsync(responseCB, inA->exception(), current);
    return false;
}

bool
argo::Foo::_iceD_doitAgain(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    auto inA = ::IceInternal::IncomingAsync::create(inS);
    auto responseCB = [inA](const ::std::string& ret)
    {
        auto ostr = inA->startWriteParams();
        ostr->writeAll(ret);
        inA->endWriteParams();
        inA->completed();
    };
    this->doitAgainAsync(responseCB, inA->exception(), current);
    return false;
}

bool
argo::Foo::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_argo_Foo_ops, iceC_argo_Foo_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_argo_Foo_ops)
    {
        case 0:
        {
            return _iceD_doit(in, current);
        }
        case 1:
        {
            return _iceD_doitAgain(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
argo::FooPrx::_iceI_doit(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_argo_Foo_doit_name);
    outAsync->invoke(iceC_argo_Foo_doit_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

void
argo::FooPrx::_iceI_doitAgain(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_argo_Foo_doitAgain_name);
    outAsync->invoke(iceC_argo_Foo_doitAgain_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
argo::FooPrx::_newInstance() const
{
    return ::IceInternal::createProxy<FooPrx>();
}

const ::std::string&
argo::FooPrx::ice_staticId()
{
    return argo::Foo::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_argo_Foo_doit_name = "doit";

const ::std::string iceC_argo_Foo_doitAgain_name = "doitAgain";

}

argo::AMD_Foo_doit::~AMD_Foo_doit()
{
}

argo::AMD_Foo_doitAgain::~AMD_Foo_doitAgain()
{
}

IceAsync::argo::AMD_Foo_doit::AMD_Foo_doit(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::argo::AMD_Foo_doit::ice_response(const ::std::string& ret)
{
    ::Ice::OutputStream* ostr = startWriteParams();
    ostr->write(ret);
    endWriteParams();
    completed();
}

IceAsync::argo::AMD_Foo_doitAgain::AMD_Foo_doitAgain(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::argo::AMD_Foo_doitAgain::ice_response(const ::std::string& ret)
{
    ::Ice::OutputStream* ostr = startWriteParams();
    ostr->write(ret);
    endWriteParams();
    completed();
}
::IceProxy::Ice::Object* ::IceProxy::argo::upCast(::IceProxy::argo::Foo* p) { return p; }

void
::IceProxy::argo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::argo::Foo>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::argo::Foo;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::argo::Foo::_iceI_begin_doit(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_argo_Foo_doit_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_argo_Foo_doit_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_argo_Foo_doit_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_argo_Foo_doit_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::argo::Foo::end_doit(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_argo_Foo_doit_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::argo::Foo::_iceI_begin_doitAgain(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_argo_Foo_doitAgain_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_argo_Foo_doitAgain_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_argo_Foo_doitAgain_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_argo_Foo_doitAgain_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::argo::Foo::end_doitAgain(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_argo_Foo_doitAgain_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::IceProxy::Ice::Object*
IceProxy::argo::Foo::_newInstance() const
{
    return new Foo;
}

const ::std::string&
IceProxy::argo::Foo::ice_staticId()
{
    return ::argo::Foo::ice_staticId();
}

argo::Foo::~Foo()
{
}

::Ice::Object* argo::upCast(::argo::Foo* p) { return p; }


namespace
{
const ::std::string iceC_argo_Foo_ids[2] =
{
    "::Ice::Object",
    "::argo::Foo"
};

}

bool
argo::Foo::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_argo_Foo_ids, iceC_argo_Foo_ids + 2, s);
}

::std::vector< ::std::string>
argo::Foo::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_argo_Foo_ids[0], &iceC_argo_Foo_ids[2]);
}

const ::std::string&
argo::Foo::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
argo::Foo::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::argo::Foo";
    return typeId;
#else
    return iceC_argo_Foo_ids[1];
#endif
}

bool
argo::Foo::_iceD_doit(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->doit_async(new IceAsync::argo::AMD_Foo_doit(inS), current);
    return false;
}

bool
argo::Foo::_iceD_doitAgain(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->doitAgain_async(new IceAsync::argo::AMD_Foo_doitAgain(inS), current);
    return false;
}

namespace
{
const ::std::string iceC_argo_Foo_all[] =
{
    "doit",
    "doitAgain",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
argo::Foo::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_argo_Foo_all, iceC_argo_Foo_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_argo_Foo_all)
    {
        case 0:
        {
            return _iceD_doit(in, current);
        }
        case 1:
        {
            return _iceD_doitAgain(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
argo::Foo::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::argo::Foo, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
argo::Foo::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::argo::Foo, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
argo::_icePatchObjectPtr(FooPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::argo::FooPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::argo::Foo::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
